### ISSUE TITLE
This package should extends doctrine, not duplicate it

### ISSUE THREAD

**Issue by esynaps** [PandawanTechnology/neo4j-data-fixtures#2]
This package can not integrate properly with other vendors. For that, it would be necessary for this class (among others)
https://github.com/PandawanTechnology/neo4j-data-fixtures/blob/58701f30f3de9c848308623c5e773aada106a2aa/src/Executor.php#L7
 to extend correctly _/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php_
which would allow it to integrate with other packages like https://github.com/liip/LiipFunctionalTestBundle

**Comment by xavismeh** [comment]
Hello @esynaps, as you can imagine, this was my original idea. But to use the exemple you've mentioned, the `AbstractExecutor` expects already a `Doctrine\Common\Persistence\ObjectManager` instance in its constructor that we don't have/want

**Comment by esynaps** [comment]
In this case, if this package had [neo4j-php-ogm](https://github.com/graphaware/neo4j-php-ogm)  in dependency, would that be possible since the graphaware EntityManager extends ObjectManager from Doctrine ?

https://github.com/graphaware/neo4j-php-ogm/blob/master/src/EntityManagerInterface.php

**Comment by xavismeh** [comment]
Actually that's slightly more complicated:
1. this **library** (!= symfony bundle) is not meant to work with a specific "external" dependency (neo4j-php-ogm in this case)
2. I think long discussions have been held for years (!) between @ikwattro and doctrine' team but no agreement on integration have been found so far (different behavior, etc...)

**Comment by esynaps** [comment]
Thanks for the information. It's too bad this library is not usable in my case.
